O conjunto de dados Iris, inclui três espécies de íris com 50 amostras cada, bem como algumas propriedades sobre cada flor. Uma espécie de flor é linearmente separável das outras duas, mas as outras duas não são linearmente separáveis uma da outra.

As colunas neste conjunto de dados são:

*   Id
*   Comprimento(cm) da Sépala
*   Largura(cm) Sépala
*   Comprimento(cm) da pétala
*   Largura(cm) da pétala
*   Espécie


In [3]:
# CARREGANDO AS BIBLIOTECAS
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.model_selection import cross_val_score
import numpy as np

# DEFININDO O CONJUNTO DE DADOS
iris = datasets.load_iris()

In [4]:
iris.data
# vai mostrar o dataset completo com as 4 colunas: comprimento e largura da sépala | comprimento e largura da pétala

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
# Mostra os tipos de IRIS que existem na lista. Amostra de 150, com 3 tipos distintos.

# 0 = tipo 1
# 1 = tipo 2
# 2 = tipo 3

iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
# Criando objeto com o algoritmo de classificação de arvore de decisão
clf = DecisionTreeClassifier()

# Função para treinar a máquina, com os valores detalhados de cada especie e prevendo a classificação de cada posição para o seu resultado
clf.fit(iris.data,iris.target)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [7]:
# Mostra a importância de cada variável no dataset
# Quanto mais próximo de 1, é importante
clf.feature_importances_

array([0.        , 0.01333333, 0.06405596, 0.92261071])

In [8]:
# Mostra o nome das colunas do dataset
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

Começando a predição do tipo da espécie

In [9]:
# Item abaixo é do tipo 1
iris.data[0]

# No comando abaixo, o algoritmo vai fazer uma predição do tipo de iris, no caso passando um array com os detalhes da flor
# Vai me retornar como array, o dado que mostra o classificação do tipo de iris
clf.predict([iris.data[0]])
# Indice 0 correspondente ao tipo 1

array([0])

Medindo a taxa de acertividade do modelo

In [10]:
# Depois que o modelo está treinado com os dados e suas classificações relativas
# O modelo vai tentar prever a classificação dos tipos com base nos dados que eu vou passar para ele
pred = clf.predict(iris.data)

# Ele vai medir a taxa de acerto que eu tive nas previsões comparando com as classificações exatas que eu possuia antes dos tipos
# O indicado é ficar próximo de 1, e não dar esse valor exato
metrics.accuracy_score(iris.target, pred)

1.0

Erros de treino:

In [11]:
# Treino meu modelo novamente mas somente com os 30 tipos finais, assim não sendo treinada com todos os tipos existentes
clf.fit(iris.data[:120], iris.target[:120])

# Faço a previsão
pred = clf.predict(iris.data[120:])

# Meço a taxa de acerto
metrics.accuracy_score(iris.target[120:], pred)

0.7333333333333333

In [12]:
# Comparativo entre os tipos da previsão e os 'reais'
# Não conseguiu fazer a predição correta do terceiro tipo, porque não viu dados suficientes do segundo tipo e assim ficou treinada somente por ter tido mais exemplos do terceiro tipo
iris.target[120:],pred

(array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2]),
 array([2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2]))

Fazendo uma validação melhorada...

In [13]:
score = cross_val_score(clf,iris.data, iris.target, cv=10)
# Com a quantidade de 10 interações, a função proporcionalmente vai ter um aprendizado de 90% e treinando em 10%.

# Ele vai retornar um array com 10 valores...que ao tirar a média vai mostrar a taxa de acerto
np.mean(score)

0.9533333333333334